"""empty message

Revision ID: 77a87b148b1d
Revises: 
Create Date: 2024-11-01 18:38:01.368463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77a87b148b1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entrada', schema=None) as batch_op:
        batch_op.alter_column('DataEntrada',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('Saida', schema=None) as batch_op:
        batch_op.alter_column('Valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('Tipo_Entrada', schema=None) as batch_op:
        batch_op.alter_column('Data_Criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('Tipo_de_Saida', schema=None) as batch_op:
        batch_op.alter_column('Nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('Data_Criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.alter_column('Salt',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['Email'])
        batch_op.create_unique_constraint(None, ['CPF'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('Salt',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    with op.batch_alter_table('Tipo_de_Saida', schema=None) as batch_op:
        batch_op.alter_column('Data_Criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('Nome',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('Tipo_Entrada', schema=None) as batch_op:
        batch_op.alter_column('Data_Criacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('Saida', schema=None) as batch_op:
        batch_op.alter_column('Valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('Entrada', schema=None) as batch_op:
        batch_op.alter_column('DataEntrada',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
