-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Entrada"
(
    "Descricao" character varying COLLATE pg_catalog."default",
    "Valor" double precision,
    "DataEntrada" timestamp without time zone NOT NULL,
    "ID" serial NOT NULL,
    "ID_Tipo_Entrada" integer,
    "Id_Usuario" integer,
    "DataRegistro" timestamp without time zone[],
    CONSTRAINT "Entrada_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Saida"
(
    "Descricao" character varying COLLATE pg_catalog."default",
    "Valor" double precision NOT NULL,
    "Data_Vencimento" timestamp without time zone,
    "ID" serial NOT NULL,
    "ID_Tipo_Saida" integer,
    "ID_Usuario" integer,
    "DataRegistro" timestamp without time zone[],
    CONSTRAINT "Saida_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Tipo_Entrada"
(
    "ID" serial NOT NULL,
    "Nome" character varying COLLATE pg_catalog."default" NOT NULL,
    "Data_Criacao" timestamp without time zone NOT NULL,
    "Id_Usuario" integer,
    icone character varying[] COLLATE pg_catalog."default",
    CONSTRAINT "Tipo_Entrada_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Tipo_de_Saida"
(
    "Nome" character varying COLLATE pg_catalog."default",
    "Data_Criacao" timestamp without time zone NOT NULL,
    "ID" serial NOT NULL,
    "Id_Usuario" integer,
    icone character varying[] COLLATE pg_catalog."default",
    CONSTRAINT "Tipo_de_Saida_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Usuario"
(
    "Nome" character varying(60) COLLATE pg_catalog."default" NOT NULL,
    "Sobrenome" character varying(60) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying COLLATE pg_catalog."default" NOT NULL,
    "Senha" character varying COLLATE pg_catalog."default" NOT NULL,
    "CPF" character varying COLLATE pg_catalog."default" NOT NULL,
    "ID" serial NOT NULL,
    "Salt" bytea NOT NULL,
    CONSTRAINT "Usuario_pkey" PRIMARY KEY ("CPF"),
    CONSTRAINT "Usuario_ID_key" UNIQUE ("ID")
);

ALTER TABLE IF EXISTS public."Entrada"
    ADD CONSTRAINT "Entrada_ID_Tipo_Entrada_fkey" FOREIGN KEY ("ID_Tipo_Entrada")
    REFERENCES public."Tipo_Entrada" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Entrada"
    ADD CONSTRAINT "Entrada_Id_Usuario_fkey" FOREIGN KEY ("Id_Usuario")
    REFERENCES public."Usuario" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Saida"
    ADD CONSTRAINT "Saida_ID_Tipo_Saida_fkey" FOREIGN KEY ("ID_Tipo_Saida")
    REFERENCES public."Tipo_de_Saida" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Saida"
    ADD CONSTRAINT "Saida_ID_Usuario_fkey" FOREIGN KEY ("ID_Usuario")
    REFERENCES public."Usuario" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Tipo_Entrada"
    ADD CONSTRAINT "Tipo_Entrada_Id_Usuario_fkey" FOREIGN KEY ("Id_Usuario")
    REFERENCES public."Usuario" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Tipo_de_Saida"
    ADD CONSTRAINT "Tipo_de_Saida_Id_Usuario_fkey" FOREIGN KEY ("Id_Usuario")
    REFERENCES public."Usuario" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;